DROP TABLE IF EXISTS CLIENTE , VEICULO , CLIENTE_TEM_VEICULO, REPARO, PECA , REPARO_USA_PECA, MECANICO, ESPECIALIDADE, MECANICO_TEM_ESPECIALIDADE, ESTOQUE , FORNECEDOR, ESTOQUE_TEM_FORNECEDOR;

CREATE TABLE CLIENTE(
id_cliente INTEGER PRIMARY KEY,
telefone_cliente INTEGER,
end_cliente VARCHAR (100)

);
CREATE TABLE VEICULO(
placa VARCHAR (30) PRIMARY KEY,
marca_carro VARCHAR (50),
modelo_carro VARCHAR(50)

);
CREATE TABLE CLIENTE_TEM_VEICULO(
id_cliente INTEGER,
placa_carro VARCHAR(30),
FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente),
FOREIGN KEY (placa_carro) REFERENCES VEICULO (placa)
);
CREATE TABLE REPARO(
id_reparo INTEGER PRIMARY KEY,
data_reparo INTEGER,
custo_reparo INTEGER
);

CREATE TABLE PECA(
id_peca INTEGER PRIMARY KEY,
designacao VARCHAR (200),
custo_peca INTEGER
);

CREATE TABLE REPARO_USA_PECA(
id_reparo INTEGER,
id_peca INTEGER,
FOREIGN KEY (id_reparo) REFERENCES REPARO (id_reparo),
FOREIGN KEY (id_peca) REFERENCES PECA (id_peca)
);
CREATE TABLE MECANICO (
horas_trabalhadas INTEGER ,
id_mec INTEGER PRIMARY KEY,
salario_mec INTEGER

);
CREATE TABLE ESPECIALIDADE(
area_atuacao VARCHAR (200),
nome_esp VARCHAR (100) PRIMARY KEY,
custo_esp INTEGER
);
CREATE TABLE MECANICO_TEM_ESPECIALIDADE(
id_mec INTEGER,
nome_esp VARCHAR (100),
FOREIGN KEY (id_mec) REFERENCES MECANICO (id_mec),
FOREIGN KEY (nome_esp) REFERENCES ESPECIALIDADE(nome_esp)
);
CREATE TABLE ESTOQUE (
id_peca INTEGER PRIMARY KEY,
nome_peca VARCHAR (200),
quantidade_peca INTEGER UNIQUE,
FOREIGN KEY (id_peca) REFERENCES PECA(id_peca)
);
CREATE TABLE FORNECEDOR(
CNPJ INTEGER PRIMARY KEY,
logradouro VARCHAR(300),
telefone_fornecedor INTEGER
);
CREATE TABLE ESTOQUE_TEM_FORNECEDOR(
CNPJ INTEGER,
quantidade_peca INTEGER,
FOREIGN KEY (quantidade_peca) REFERENCES ESTOQUE (quantidade_peca),
FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR (CNPJ)

);
#Guilherme dos Santos Fernandes 2304325
#https://github.com/GuilhermeSFernandes/Projeto-BD1


